import type { Metadata } from "next";
import Footer from "./common/Footer";
import Header from "./common/Header";
import "./globals.css";



export const metadata: Metadata = {
  title: "Mess Mania",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
